blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    # favicon
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

    # site skeleton urls
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_page, name='login-page'),
    url(r'^logout/', views.logout_page, name='logout-page'),
    url(r'^about/', views.about, name='about'),
    url(r'^books/', views.books, name='books'),
    url(r'^highlights/', views.highlights, name='highlights'),
    url(r'^ideas/$', views.ideas, name='catalog'),
    url(r'^ideas/(?P<idea_slug>[a-z0-9\-]+)/$', views.idea_detail, name='idea-page'),
    url(r'^ideas/(?P<idea_slug>[a-z0-9\-]+)/(?P<thought_slug>[a-z0-9\-]+)/', views.thought_detail, name='thought-page'),

    # dashboard urls, admin only!
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/books/$', views.dashboard_books, name='dashboard-books'),
    url(r'^dashboard/highlights/$', views.dashboard_highlights, name='dashboard-highlights'),
    url(r'^dashboard/tasks/$', views.dashboard_todo, name='dashboard-todo'),
    url(r'^dashboard/notes/$', views.dashboard_notes, name='dashboard-notes'),
    url(r'^dashboard/ideas/$', views.dashboard_ideas, name='dashboard-ideas'),
    url(r'^dashboard/thoughts/$', views.dashboard_thoughts, name='dashboard-thoughts'),
    url(r'^dashboard/author/$', views.dashboard_author, name='dashboard-author'),
    url(r'^dashboard/drafts/$', views.dashboard_drafts, name='dashboard-drafts'),
    url(r'^dashboard/trash/$', views.dashboard_trash, name='dashboard-trash'),
    url(r'^dashboard/backend/$', views.dashboard_backend, name='dashboard-backend'),

    # site api
    url(r'^api/login/', views.login, name='login'),
    url(r'^api/logout/', views.logout, name='logout'),
    url(r'^api/upload/', views.upload, name='upload'),
    url(r'^api/generate_upload_filename(?P<full_path>(\/full)?)/(?P<filename>.*)', views.generate_upload_filename, name='generate-upload-filename'),
    url(r'^api/search_books/(?P<keywords>.*)', views.search_books, name='search-books'),

    url(r'^api/forms/idea/', views.FormIdeaView.as_view(), name='forms-idea'),
    url(r'^api/forms/thought/', views.FormThoughtView.as_view(), name='forms-thought'),
    url(r'^api/forms/highlight/', views.FormHighlightView.as_view(), name='forms-highlight'),
    url(r'^api/forms/readinglistitem/', views.FormReadingListView.as_view(), name='forms-readinglistitem'),
    url(r'^api/forms/task/$', views.FormTaskView.as_view(), name='forms-task'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/mark', views.FormTaskView.mark_complete, name='forms-task-mark'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/priority/(?P<priority>[0-9]+)', views.FormTaskView.change_priority, name='forms-task-priority'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/delete', views.FormTaskView.delete, name='forms-task-delete'),
    url(r'^api/forms/note/$', views.FormNoteView.as_view(), name='forms-note'),
    url(r'^api/forms/note/(?P<id>[0-9]+)/associate_idea/(?P<idea_slug>[a-z0-9\-]+)', views.FormNoteView.add_idea, name='forms-note-associate-idea'),
    url(r'^api/forms/note/(?P<id>[0-9]+)/associate_thought/(?P<thought_slug>[a-z0-9\-]+)', views.FormNoteView.add_thought, name='forms-note-associate-thought'),
]

# setup serving of media asserts on development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

brainstorm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers

from blog import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'ideas', views.IdeaViewSet)
router.register(r'thoughts', views.ThoughtViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'brainstorm.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^', include('blog.urls', namespace='blog')),
    url(r'^blog(/?)', include('blog.urls', namespace='blog')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^api(/?)', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

slackerparadise/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('blog.urls')),
]

blog/models.py
import os
import json
import datetime
import urllib

import pytz
from imagekit.models import ImageSpecField
from imagekit.processors import Crop
from bs4 import BeautifulSoup

from django.db import models
from django.db.models import Max
from django.db.models.query import QuerySet
from django.conf import settings
from django.contrib.auth.models import User

import paths
from blog import lib


###############################################################################
# Idea model
###############################################################################
class Idea(models.Model):
    """ In other blogs, this would be called a "Category", but I want to
        connote a sense of progression on a line of inquiry or research. For
        instance, an Idea could be a "video game idea" and Thoughts
        associated with the Idea would be progress/status updates containing
        maybe screen shots, videos, and even code snippets.
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(primary_key=True)
    description = models.TextField()
    order = models.IntegerField(unique=True)
    icon = models.ImageField(
        upload_to=paths.MEDIA_IMAGE_DIR,
        blank=False,
        null=False,
    )
    icon_small = ImageSpecField(
        source='icon',
        processors=[Crop(
            width=lib.IDEA_PREVIEW_IMAGE_SMALL_SIZE[0],
            height=lib.IDEA_PREVIEW_IMAGE_SMALL_SIZE[1],
            anchor=(0.5, 0.5),
        )],
        format='png',
        options={'quality': '70'},
    )

    # non field members
    allowed_tags = [
        'abbr', 'ul', 'code', 'em', 'strong', 'li', 'ol', 'p',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'br'
    ]

    def get_next(self):
        """ get the next Idea by order column or return
            None if this Idea instance is the latest
        """
        try:
            return Idea.objects.filter(order__gt=self.order).order_by('order')[0]
        except IndexError:
            return None

    def get_prev(self):
        """ get the previous Idea by order column or return
            None if this Idea instance is the first
        """
        try:
            return Idea.objects.filter(order__lt=self.order).order_by('-order')[0]
        except IndexError:
            return None

    def strip_tags(self):
        """ strip all html tags from content field and return the content field
        """
        return lib.strip_tags(self.description)

    def truncate(self, max_length=270, allowed_tags=None, full_link=None):
        """ output a form of the content field, truncated to max_length. Tags
            will be whitelisted, stripped, and balanced to account for
            truncation.
        """
        return lib.truncate(
            content=self.description,
            allowed_tags=allowed_tags or self.allowed_tags,
            max_length=max_length,
            full_link=full_link,
        )

    def save(self, *args, **kwargs):
        """ if order field is None, add value (1 + maximum existing value)
        """
        if not self.order:
            idea_idx = Idea.objects.all().aggregate(Max('order'))['order__max']
            if idea_idx:
                idea_idx += 1
            else:
                idea_idx = 1
            self.order = idea_idx

        # "real" save method
        super(Idea, self).save(*args, **kwargs)

        if self.icon:
            lib.resize_image(self.icon.name, new_size=lib.IDEA_PREVIEW_IMAGE_SIZE)

    def delete(self, *args, **kwargs):
        lib.delete_file(self.icon.name)
        super(Idea, self).delete(*args, **kwargs)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return self.name


###############################################################################
# Thought model
###############################################################################
class Thought(models.Model):
    """ Thought class corresponds roughly to a blog post. The intention
        is to have many child classes of Thought to include different types
        of multimedia. For example, posts in a "comic" idea would ideally
        contain one required comic picture along with a relatively short
        text description.
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(primary_key=True)
    content = models.TextField(blank=True, null=True)
    idea = models.ForeignKey(Idea)
    author = models.ForeignKey(User)
    is_draft = models.BooleanField(default=True)
    is_trash = models.BooleanField(default=False)
    date_published = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    preview = models.ImageField(
        upload_to=paths.MEDIA_IMAGE_DIR,
        blank=True,
        null=True,
    )

    # non field members
    allowed_tags = [
        'abbr', 'ul', 'code', 'em', 'strong', 'li', 'ol', 'p',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'br'
    ]

    def strip_tags(self):
        """ strip all html tags from content field and return the content field
        """
        return lib.strip_tags(self.content)

    def truncate(self, max_length=250, allowed_tags=None, full_link=None):
        """ output a form of the content field, truncated to max_length. Tags
            will be whitelisted, stripped, and balanced to account for
            truncation.
        """
        return lib.truncate(
            content=self.content,
            max_length=max_length,
            allowed_tags=allowed_tags or self.allowed_tags,
            full_link=full_link,
        )

    def get_preview(self):
        """ safe way to get preview url for this thought. Will return None if
            there is no preview picture. Use template tag |default_if_none:
            to handle template output of this function.
        """
        if self.preview and hasattr(self.preview, 'url'):
            return self.preview.url
        return self.idea.icon.url

    def get_next_thoughts(self, num=1, include_drafts=False, include_trash=False):
        """ get the next "num" thoughts in the same Idea and return a list
            of Thought objects. This list will be padded with None types such
            that it will be of length "num" always.
        """
        query_params = {
            'idea': self.idea,
            'is_draft': include_drafts,
            'is_trash': include_trash,
            'date_published__gt': self.date_published,
        }

        # note: assumes Thoughts are ordered chronologically. Reasonable
        # assumption; may change in the far future, don't worry about it
        thought_list = Thought.objects.filter(**query_params).order_by('date_published')[:num]

        # pull out thoughts in reverse order
        adjacent_thoughts = [t for idx, t in enumerate(thought_list)]

        # add padding
        adjacent_thoughts += [None] * (num - len(adjacent_thoughts))
        return adjacent_thoughts

    def get_prev_thoughts(self, num=1, include_drafts=False, include_trash=False):
        """ get the previous "num" thoughts in the same Idea and return a list
            of Thought objects. This list will be padded with None types such
            that it will be of length "num" always.
        """
        query_params = {
            'idea': self.idea,
            'is_draft': include_drafts,
            'is_trash': include_trash,
            'date_published__lt': self.date_published,
        }

        # note: assumes Thoughts are ordered chronologically. Reasonable
        # assumption; may change in the far future, don't worry about it
        thought_list = Thought.objects.filter(**query_params).order_by('-date_published')[:num]

        # pull out thoughts in reverse order
        adjacent_thoughts = [t for idx, t in enumerate(thought_list)]

        # add padding
        adjacent_thoughts += [None] * (num - len(adjacent_thoughts))
        return adjacent_thoughts

    def is_edited(self, delta=datetime.timedelta(minutes=1)):
        """ compare date_published and date_edited with margin of error and
            return a boolean (True if date_published != date_edited and
            False if date_published == date_edited, within margin of error)
        """
        if self.date_edited - self.date_published < delta:
            return False
        return True

    def get_image_urls(self):
        """ parse the html in the content field and return a list of
            image urls (relative to media url) for processing
        """
        soup = BeautifulSoup(self.content)
        return [image['src'] for image in soup.findAll('img')]

    def display_compact_date(self):
        return lib.display_compact_date(self.date_published)

    def save(self, *args, **kwargs):
        # check to see if this save means a draft is being published and
        # change date_published to now
        auto_update = kwargs['auto_update'] if 'auto_update' in kwargs else True
        try:
            if auto_update:
                orig = Thought.objects.get(slug=self.slug)
                if orig.is_draft and not self.is_draft:
                    self.date_published = pytz.timezone(settings.TIME_ZONE).localize(datetime.datetime.now())
        except Thought.DoesNotExist:
            pass

        # "real" save method
        super(Thought, self).save()

        # crop picture if necessary
        if not self.preview:
            return

        lib.resize_image(self.preview.name, lib.THOUGHT_PREVIEW_IMAGE_SIZE)

    def delete(self, *args, **kwargs):
        lib.delete_file(self.preview.name)

        # remove inline images
        for image in self.get_image_urls():
            image = os.path.basename(image)
            image = os.path.join(paths.MEDIA_IMAGE_DIR, image)
            lib.delete_file(image)

        super(Thought, self).delete(*args, **kwargs)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):

blog/templates/blog/dashboard/dashboard.html
{% extends 'blog/templates/template_dashboard.html' %}
{% load staticfiles %}
{% load blog_extras %}

{% block http_headers %}
{% endblock %}

{% block content %}
<h2>{{ request.user.username }}'s Recent Activity</h2>
<table class="activity-feed">
    <tbody>
    {% for activity in activities %}
    <tr>
        <td class="shrink">
            <div class="activity-type-{{ activity.type }}"></div>
        </td>
        <td>
            {% if activity.url %}
            <a class="overlay" href="{{ activity.url }}"></a>
            {% endif %}
            <p>{% if activity.author == request.user %}You{% else %}{{ activity.author }}{% endif %} {{ activity.generate_message|safe }}</p>
        </td>
        <td class="shrink right-justify date">{{ activity.display_date }}</td>
    </tr>
    {% empty %}
    <tr>
        <td class="shrink"><div class="activity-type-"></div></td>
        <td>No recent activity...</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

{% include "blog/templates/template_pagination.html" with paginator=paginator pages=pagination %}
{% endblock %}

blog/templates/blog/dashboard/dashboard_author.html
{% extends 'blog/templates/template_dashboard.html' %}
{% load staticfiles %}
{% load blog_extras %}

{% block http_headers %}
<script type="text/javascript">
  // page specific javascript init shit
  $(function() {
    // fancy editor window for admins who have javascript
    initialize_tinymce({
      auto_focus: 'id_content',
      content_css: ['{% static "css/mce.css" %}'],
    });
  });
</script>
{% endblock %}

{% block content %}
{% if "id" in request.GET %}
<h2>Edit Thought</h2>
{% else %}
<h2>Write New Thought</h2>
{% endif %}

<form id="form-thought" action="{% url 'forms-thought' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% for field in thought_form.hidden_fields %}
    {{ field }}{% endfor %}
    <table>
        <tr>
            <td class="shrink">{{ thought_form.title.label_tag }}</td>
            <td class="expand">{{ thought_form.title }}</td>
        </tr>
        <tr>
            <td>{{ thought_form.slug.label_tag }}</td>
            <td class="shrink">
                {% if thought_form.slug.value %}
                <p id="id_slug" class="no-text-overflow">{{ thought_form.slug.value }}</p>
                {% else %}
                {{ thought_form.slug }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <td>{{ thought_form.preview.label_tag }}</td>
            <td class="expand no-text-overflow">{{ thought_form.preview }}</td>
        </tr>
        <tr>
            <td>{{ thought_form.idea.label_tag }}</td>
            <td class="shrink">
                {% if not idea %}
                {{ thought_form.idea }}
                {% endif %}
            </td>
        </tr>
        <tr>
            <td colspan="3">{{ thought_form.content }}</td>
        </tr>
        <tr>
            <td colspan="3">
                <input id="button-clear" type="button" value="Clear" />
                <input id="button-revert" type="button" value="Revert" />

                {% if thought_form.is_draft.value == True %}
                <button type="submit" name="is_draft" value="True">Save</button>
                <button type="submit" name="is_draft" value="False" class="publish right">Publish</button>
                {% else %}
                {% if "id" not in request.GET %}
                <button type="submit" name="is_draft" value="True">Save as Draft</button>
                <button type="submit" name="is_draft" value="False" class="publish right">Publish</button>
                {% else %}
                <button type="submit" name="is_draft" value="False" class="publish right">Edit</button>
                {% endif %}
                {% endif %}
            </td>
        </tr>
    </table>
</form>
{% endblock %}

{% block side %}
<div class="todo-box">
    <h3>Related Tasks</h3>
    {% get_latest_tasks name='todo_list_tasks' length=5 idea=thought_form.idea.value %}

    <table class="task-list">
        <tbody>
        {% for task in todo_list_tasks %}
        <tr>
            <td class="shrink">
                {% if not task.parent_task and not task.has_subtasks %}
                    {% if task.is_completed %}
                    <img class="icon icon-checkbox" src="{% static 'images/icon_checkbox.png' %}">
                    {% else %}
                    <a class="incomplete icon icon-checkbox" title="Mark as Complete" href="{% url 'forms-task-mark' task.id %}"></a>
                    {% endif %}
                {% endif %}
            </td>
            <td>
                {% if task.parent_task %}
                    {% if task.is_completed %}
                    <img class="icon icon-checkbox" src="{% static 'images/icon_checkbox.png' %}">
                    {% else %}
                    <a class="incomplete icon icon-checkbox" title="Mark as Complete" href="{% url 'forms-task-mark' task.id %}"></a>
                    {% endif %}
                    &nbsp;
                {% endif %}

                <span class="priority_{{ task.priority }}">
                    {{ task.content }}
                    {% if task.idea %}
                    <span class="slug blue">{{ task.idea }}</span>
                    {% endif %}
                </span>
            </td>
            <td class="shrink center-align">
                {% if not task.is_completed %}
                <a class="dropdown priority-dropdown"></a>
                <ul class="dropdown">
                    <li><a title="Change to Next Priority" href="{% url 'forms-task-priority' task.id 3 %}">next</a></li>
                    <li><a title="Change to High Priority" href="{% url 'forms-task-priority' task.id 2 %}">high</a></li>
                    <li><a title="Change to Medium Priority" href="{% url 'forms-task-priority' task.id 1 %}">med</a></li>
                    <li><a title="Change to Low Priority" href="{% url 'forms-task-priority' task.id 0 %}">low</a></li>
                </ul>
                {% endif %}
            </td>
            <td class="shrink center-align">
                <a class="icon icon-delete" title="Delete this task" href="{% url 'forms-task-delete' task.id %}"></a>
            </td>
        </tr>
        {% if forloop.last %}
        <tr>
            <td colspan="4" class="center-align"><a href="{% url 'dashboard-todo' %}">More Tasks...</a></td>
        </tr>
        {% endif %}
        {% empty %}
        <tr><td>No relevant Tasks.</td></tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<div class="note-box">
    <h3>Relevant Notes</h3>
    {% if thought_form.edit %}
      {% get_latest_notes name='latest_notes' length=7 idea=thought_form.idea.value thought=thought_form.edit.value %}
    {% else %}
      {% get_latest_notes name='latest_notes' length=7 idea=thought_form.idea.value %}
    {% endif %}

    <table class="note-list">
        <tbody>
        {% for note in latest_notes %}
        <tr>
            <td>
                <a class="overlay" href="{% url 'dashboard-notes' %}?id={{ note.id }}"></a>

                <span class="title green">{{ note.title }}</span>
                <span class="date blue">{{ note.date_published|date:"F j, Y, g:i A" }}</span>
                {{ note.content|safe }}
            </td>
        </tr>
        {% empty %}
        <tr><td class="center-align">There are no Notes in the database.</td></tr>
        {% endfor %}
        <tr>
            <td class="center-align">
                <a class="more" href="{% url 'dashboard-notes' %}">More Notes...</a>
            </td>
        </tr>
        </tbody>
    </table>
</div>
{% endblock %}

{% block footer %}
<p>
    <a href="{% url 'dashboard' %}">Dashboard</a> //
    {% if "id" in request.GET %}
    <a href="{% url 'dashboard-ideas' %}">{{ thought_form.idea.value }}</a> //
    <a href="{% url 'dashboard-thoughts' %}?id={{ thought_form.idea.value|default_if_none:'' }}">{{ thought_form.title.value }}</a> //
    Edit Thought //
    {% else %}
    <a href="{% url 'dashboard-ideas' %}">Content</a> //
    <a href="{% url 'dashboard-thoughts' %}">Thoughts</a> //
    Post New Thought //
    {% endif %}
    {{ request.user }}
</p>
{% endblock %}

blog/templates/blog/dashboard/dashboard_books.html
{% extends 'blog/templates/template_dashboard.html' %}
{% load staticfiles %}
{% load blog_extras %}

{% block http_headers %}
<script type="text/javascript">
  $(function() {
    /* add event to search bar on enter keypress */
    $('#book-search-bar').keypress(book_search_enter_triggered);

    /* add event to search bar button on click */
    $('#book-search img').click(book_search);

    /* javascript clear button */
    $('#button-clear').click(function () {
      prefill_form('reading-list-form', {
        'id_title': '',
        'id_author': '',
        'id_link': '',
        'id_cover': '',
        'id_description': '',
        'id_wishlist': false,
        'id_favorite': false,
      });

      /* remove id hidden field */
      $('#id_id').remove();
    });

    /* add confirm dialog to delete buttons on book lists */
    $('.book-list').delegate('.delete-icon', 'click', function () {
      var msg = 'Really delete?';
      var result = confirm(msg);

      if (!result) {
        return false;
      }
    });
  });
</script>
{% endblock %}

{% block content %}
<h2>Recently Read Books</h2>

<h3>Currently Reading</h3>
<div class="book-list">
    {% for book in wish_list %}
    <div class="book-book-result group">
        <img src="{{ book.cover }}" class="left">
        <p class="title">{{ book.title }}</p>
        <p class="author">{{ book.author }}</p>
        <p class="description">{{ book.description }}</p>
        <p class="date">Added on {{ book.date_published|date:"F j, Y g:i A" }}</p>
        {% if book.favorite %}<span class="favorite" title="Cory's Favorites">&#x2605;</span>{% endif %}
        <a class="link-icon" href="{{ book.link }}" target="_blank" title="Open external link"></a>
        <a class="link-icon edit-icon" href="{% url 'dashboard-books' %}?id={{ book.id }}" title="Edit"></a>
        <form action="{% url 'dashboard-backend' %}" method="post">
            <input type="hidden" name="id" value="{{ book.id }}">
            <input type="hidden" name="next" value="{% url 'dashboard-books' %}">
            <input type="hidden" name="action" value="book_delete">
            {% csrf_token %}
            <input class="link-icon delete-icon" type="submit" value="" name="book_delete" title="Delete" />
        </form>
    </div>
    {% empty %}
    <p class="empty">There are no books in your currently reading list.</p>
    {% endfor %}
</div>

<h3>Recently Read</h3>
<div class="book-list">
    {% for book in read_list %}
    <div class="book-book-result group">
        <img src="{{ book.cover }}" class="left">
        <p class="title">{{ book.title }}</p>
        <p class="author">{{ book.author }}</p>
        <p class="description">{{ book.description }}</p>
        <p class="date">Added on {{ book.date_published|date:"F j, Y g:i A" }}</p>
        {% if book.favorite %}<span class="favorite" title="Cory's Favorites">&#x2605;</span>{% endif %}
        <a class="link-icon" href="{{ book.link }}" target="_blank" title="Open external link"></a>
        <a class="link-icon edit-icon" href="{% url 'dashboard-books' %}?id={{ book.id }}" title="Edit"></a>
        <form action="{% url 'dashboard-backend' %}" method="post">
            <input type="hidden" name="id" value="{{ book.id }}">
            <input type="hidden" name="next" value="{% url 'dashboard-books' %}">
            <input type="hidden" name="action" value="book_delete">
            {% csrf_token %}
            <input class="link-icon delete-icon" type="submit" value="" name="book_delete" title="Delete" />
        </form>
    </div>
    {% empty %}
    <p class="empty">There are no books in your recently read list.</p>
    {% endfor %}
</div>

{% include "blog/templates/template_pagination.html" with paginator=paginator pages=pagination %}
{% endblock %}

{% block side %}
<h3>Add New Book to Reading List:</h3>
<div id="book-search" class="group">
    <input id="book-search-url" type="hidden" value="{% url 'search-books' '' %}">
    <input id="book-search-bar" type="text" placeholder="Search for books..." class="search-bar left" />
    <img src="{% static 'images/search.png' %}" class="left">
</div>
<div id="book-results">
    <img class="loader" src="{% static 'images/loading.gif' %}">
</div>
<hr>
<form id="reading-list-form" action="{% url 'forms-readinglistitem' %}" method="post">
    {% csrf_token %}
    {% for field in reading_list_item_form.hidden_fields %}
    {{ field }}
    {% endfor %}
    <table>
        <tbody>
        <tr>
            <td class="shrink">{{ reading_list_item_form.title.label_tag }}</td>
            <td colspan="4">{{ reading_list_item_form.title }}</td>
        </tr>
        <tr>
            <td class="shrink">{{ reading_list_item_form.author.label_tag }}</td>
            <td colspan="4">{{ reading_list_item_form.author }}</td>
        </tr>
        <tr>
            <td class="shrink">{{ reading_list_item_form.link.label_tag }}</td>
            <td colspan="4">{{ reading_list_item_form.link }}</td>
        </tr>
        <tr>
            <td class="shrink">{{ reading_list_item_form.cover.label_tag }}</td>
            <td colspan="4">{{ reading_list_item_form.cover }}</td>
        </tr>
        <tr>
            <td class="shrink">{{ reading_list_item_form.description.label_tag }}</td>
            <td colspan="4">{{ reading_list_item_form.description }}</td>
        </tr>
        <tr>
            <td></td>
            <td class="shrink">{{ reading_list_item_form.wishlist.label_tag }}</td>
            <td>{{ reading_list_item_form.wishlist }}</td>
            <td class="shrink">{{ reading_list_item_form.favorite.label_tag }}</td>
            <td>{{ reading_list_item_form.favorite }}</td>
        </tr>
        <tr>
            <td></td>
            <td colspan="4">
                <button class="publish left" type="submit">{% if 'id' in request.GET %}Edit{% else %}Add{% endif %}</button>
                <button id="button-clear" class="left" type="button">Clear</button>
            </td>
        </tr>
        </tbody>
    </table>
</form>

{% stat_box %}
{% endblock %}

blog/templates/blog/dashboard/dashboard_drafts.html
{% extends 'blog/templates/template_dashboard.html' %}
{% load staticfiles %}
{% load blog_extras %}

{% block content %}
<h1>Drafts</h1>
{% include "blog/templates/template_editablelist.html" with queryset=drafts item_link="dashboard-author"|rev auto_update=True show_idea=True show_publish=True show_trash=True show_move=True %}
{% include "blog/templates/template_pagination.html" with paginator=paginator pages=pagination %}
{% endblock %}

{% block footer %}
<p><a href="{% url 'dashboard' %}">Dashboard</a> // Drafts // {{ request.user }}</p>
{% endblock %}