blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.views.generic.base import RedirectView

from . import views

urlpatterns = [
    # favicon
    url(r'^favicon\.ico$', RedirectView.as_view(url='/static/favicon.ico')),

    # site skeleton urls
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login_page, name='login-page'),
    url(r'^logout/', views.logout_page, name='logout-page'),
    url(r'^about/', views.about, name='about'),
    url(r'^books/', views.books, name='books'),
    url(r'^highlights/', views.highlights, name='highlights'),
    url(r'^ideas/$', views.ideas, name='catalog'),
    url(r'^ideas/(?P<idea_slug>[a-z0-9\-]+)/$', views.idea_detail, name='idea-page'),
    url(r'^ideas/(?P<idea_slug>[a-z0-9\-]+)/(?P<thought_slug>[a-z0-9\-]+)/', views.thought_detail, name='thought-page'),

    # dashboard urls, admin only!
    url(r'^dashboard/$', views.dashboard, name='dashboard'),
    url(r'^dashboard/books/$', views.dashboard_books, name='dashboard-books'),
    url(r'^dashboard/highlights/$', views.dashboard_highlights, name='dashboard-highlights'),
    url(r'^dashboard/tasks/$', views.dashboard_todo, name='dashboard-todo'),
    url(r'^dashboard/notes/$', views.dashboard_notes, name='dashboard-notes'),
    url(r'^dashboard/ideas/$', views.dashboard_ideas, name='dashboard-ideas'),
    url(r'^dashboard/thoughts/$', views.dashboard_thoughts, name='dashboard-thoughts'),
    url(r'^dashboard/author/$', views.dashboard_author, name='dashboard-author'),
    url(r'^dashboard/drafts/$', views.dashboard_drafts, name='dashboard-drafts'),
    url(r'^dashboard/trash/$', views.dashboard_trash, name='dashboard-trash'),
    url(r'^dashboard/backend/$', views.dashboard_backend, name='dashboard-backend'),

    # site api
    url(r'^api/login/', views.login, name='login'),
    url(r'^api/logout/', views.logout, name='logout'),
    url(r'^api/upload/', views.upload, name='upload'),
    url(r'^api/generate_upload_filename(?P<full_path>(\/full)?)/(?P<filename>.*)', views.generate_upload_filename, name='generate-upload-filename'),
    url(r'^api/search_books/(?P<keywords>.*)', views.search_books, name='search-books'),

    url(r'^api/forms/idea/', views.FormIdeaView.as_view(), name='forms-idea'),
    url(r'^api/forms/thought/', views.FormThoughtView.as_view(), name='forms-thought'),
    url(r'^api/forms/highlight/', views.FormHighlightView.as_view(), name='forms-highlight'),
    url(r'^api/forms/readinglistitem/', views.FormReadingListView.as_view(), name='forms-readinglistitem'),
    url(r'^api/forms/task/$', views.FormTaskView.as_view(), name='forms-task'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/mark', views.FormTaskView.mark_complete, name='forms-task-mark'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/priority/(?P<priority>[0-9]+)', views.FormTaskView.change_priority, name='forms-task-priority'),
    url(r'^api/forms/task/(?P<id>[0-9]+)/delete', views.FormTaskView.delete, name='forms-task-delete'),
    url(r'^api/forms/note/$', views.FormNoteView.as_view(), name='forms-note'),
    url(r'^api/forms/note/(?P<id>[0-9]+)/associate_idea/(?P<idea_slug>[a-z0-9\-]+)', views.FormNoteView.add_idea, name='forms-note-associate-idea'),
    url(r'^api/forms/note/(?P<id>[0-9]+)/associate_thought/(?P<thought_slug>[a-z0-9\-]+)', views.FormNoteView.add_thought, name='forms-note-associate-thought'),
]

# setup serving of media asserts on development environment
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT, show_indexes=True)

brainstorm/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from rest_framework import routers

from blog import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'ideas', views.IdeaViewSet)
router.register(r'thoughts', views.ThoughtViewSet)

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'brainstorm.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    #url(r'^', include('blog.urls', namespace='blog')),
    url(r'^blog(/?)', include('blog.urls', namespace='blog')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^api(/?)', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)

slackerparadise/urls.py
from django.conf.urls import include, url

urlpatterns = [
    url(r'^', include('blog.urls')),
]

blog/models.py
import os
import json
import datetime
import urllib

import pytz
from imagekit.models import ImageSpecField
from imagekit.processors import Crop
from bs4 import BeautifulSoup

from django.db import models
from django.db.models import Max
from django.db.models.query import QuerySet
from django.conf import settings
from django.contrib.auth.models import User

import paths
from blog import lib


###############################################################################
# Idea model
###############################################################################
class Idea(models.Model):
    """ In other blogs, this would be called a "Category", but I want to
        connote a sense of progression on a line of inquiry or research. For
        instance, an Idea could be a "video game idea" and Thoughts
        associated with the Idea would be progress/status updates containing
        maybe screen shots, videos, and even code snippets.
    """
    name = models.CharField(max_length=200)
    slug = models.SlugField(primary_key=True)
    description = models.TextField()
    order = models.IntegerField(unique=True)
    icon = models.ImageField(
        upload_to=paths.MEDIA_IMAGE_DIR,
        blank=False,
        null=False,
    )
    icon_small = ImageSpecField(
        source='icon',
        processors=[Crop(
            width=lib.IDEA_PREVIEW_IMAGE_SMALL_SIZE[0],
            height=lib.IDEA_PREVIEW_IMAGE_SMALL_SIZE[1],
            anchor=(0.5, 0.5),
        )],
        format='png',
        options={'quality': '70'},
    )

    # non field members
    allowed_tags = [
        'abbr', 'ul', 'code', 'em', 'strong', 'li', 'ol', 'p',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'br'
    ]

    def get_next(self):
        """ get the next Idea by order column or return
            None if this Idea instance is the latest
        """
        try:
            return Idea.objects.filter(order__gt=self.order).order_by('order')[0]
        except IndexError:
            return None

    def get_prev(self):
        """ get the previous Idea by order column or return
            None if this Idea instance is the first
        """
        try:
            return Idea.objects.filter(order__lt=self.order).order_by('-order')[0]
        except IndexError:
            return None

    def strip_tags(self):
        """ strip all html tags from content field and return the content field
        """
        return lib.strip_tags(self.description)

    def truncate(self, max_length=270, allowed_tags=None, full_link=None):
        """ output a form of the content field, truncated to max_length. Tags
            will be whitelisted, stripped, and balanced to account for
            truncation.
        """
        return lib.truncate(
            content=self.description,
            allowed_tags=allowed_tags or self.allowed_tags,
            max_length=max_length,
            full_link=full_link,
        )

    def save(self, *args, **kwargs):
        """ if order field is None, add value (1 + maximum existing value)
        """
        if not self.order:
            idea_idx = Idea.objects.all().aggregate(Max('order'))['order__max']
            if idea_idx:
                idea_idx += 1
            else:
                idea_idx = 1
            self.order = idea_idx

        # "real" save method
        super(Idea, self).save(*args, **kwargs)

        if self.icon:
            lib.resize_image(self.icon.name, new_size=lib.IDEA_PREVIEW_IMAGE_SIZE)

    def delete(self, *args, **kwargs):
        lib.delete_file(self.icon.name)
        super(Idea, self).delete(*args, **kwargs)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):
        return self.name


###############################################################################
# Thought model
###############################################################################
class Thought(models.Model):
    """ Thought class corresponds roughly to a blog post. The intention
        is to have many child classes of Thought to include different types
        of multimedia. For example, posts in a "comic" idea would ideally
        contain one required comic picture along with a relatively short
        text description.
    """
    title = models.CharField(max_length=200)
    slug = models.SlugField(primary_key=True)
    content = models.TextField(blank=True, null=True)
    idea = models.ForeignKey(Idea)
    author = models.ForeignKey(User)
    is_draft = models.BooleanField(default=True)
    is_trash = models.BooleanField(default=False)
    date_published = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)
    preview = models.ImageField(
        upload_to=paths.MEDIA_IMAGE_DIR,
        blank=True,
        null=True,
    )

    # non field members
    allowed_tags = [
        'abbr', 'ul', 'code', 'em', 'strong', 'li', 'ol', 'p',
        'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'hr', 'br'
    ]

    def strip_tags(self):
        """ strip all html tags from content field and return the content field
        """
        return lib.strip_tags(self.content)

    def truncate(self, max_length=250, allowed_tags=None, full_link=None):
        """ output a form of the content field, truncated to max_length. Tags
            will be whitelisted, stripped, and balanced to account for
            truncation.
        """
        return lib.truncate(
            content=self.content,
            max_length=max_length,
            allowed_tags=allowed_tags or self.allowed_tags,
            full_link=full_link,
        )

    def get_preview(self):
        """ safe way to get preview url for this thought. Will return None if
            there is no preview picture. Use template tag |default_if_none:
            to handle template output of this function.
        """
        if self.preview and hasattr(self.preview, 'url'):
            return self.preview.url
        return self.idea.icon.url

    def get_next_thoughts(self, num=1, include_drafts=False, include_trash=False):
        """ get the next "num" thoughts in the same Idea and return a list
            of Thought objects. This list will be padded with None types such
            that it will be of length "num" always.
        """
        query_params = {
            'idea': self.idea,
            'is_draft': include_drafts,
            'is_trash': include_trash,
            'date_published__gt': self.date_published,
        }

        # note: assumes Thoughts are ordered chronologically. Reasonable
        # assumption; may change in the far future, don't worry about it
        thought_list = Thought.objects.filter(**query_params).order_by('date_published')[:num]

        # pull out thoughts in reverse order
        adjacent_thoughts = [t for idx, t in enumerate(thought_list)]

        # add padding
        adjacent_thoughts += [None] * (num - len(adjacent_thoughts))
        return adjacent_thoughts

    def get_prev_thoughts(self, num=1, include_drafts=False, include_trash=False):
        """ get the previous "num" thoughts in the same Idea and return a list
            of Thought objects. This list will be padded with None types such
            that it will be of length "num" always.
        """
        query_params = {
            'idea': self.idea,
            'is_draft': include_drafts,
            'is_trash': include_trash,
            'date_published__lt': self.date_published,
        }

        # note: assumes Thoughts are ordered chronologically. Reasonable
        # assumption; may change in the far future, don't worry about it
        thought_list = Thought.objects.filter(**query_params).order_by('-date_published')[:num]

        # pull out thoughts in reverse order
        adjacent_thoughts = [t for idx, t in enumerate(thought_list)]

        # add padding
        adjacent_thoughts += [None] * (num - len(adjacent_thoughts))
        return adjacent_thoughts

    def is_edited(self, delta=datetime.timedelta(minutes=1)):
        """ compare date_published and date_edited with margin of error and
            return a boolean (True if date_published != date_edited and
            False if date_published == date_edited, within margin of error)
        """
        if self.date_edited - self.date_published < delta:
            return False
        return True

    def get_image_urls(self):
        """ parse the html in the content field and return a list of
            image urls (relative to media url) for processing
        """
        soup = BeautifulSoup(self.content)
        return [image['src'] for image in soup.findAll('img')]

    def display_compact_date(self):
        return lib.display_compact_date(self.date_published)

    def save(self, *args, **kwargs):
        # check to see if this save means a draft is being published and
        # change date_published to now
        auto_update = kwargs['auto_update'] if 'auto_update' in kwargs else True
        try:
            if auto_update:
                orig = Thought.objects.get(slug=self.slug)
                if orig.is_draft and not self.is_draft:
                    self.date_published = pytz.timezone(settings.TIME_ZONE).localize(datetime.datetime.now())
        except Thought.DoesNotExist:
            pass

        # "real" save method
        super(Thought, self).save()

        # crop picture if necessary
        if not self.preview:
            return

        lib.resize_image(self.preview.name, lib.THOUGHT_PREVIEW_IMAGE_SIZE)

    def delete(self, *args, **kwargs):
        lib.delete_file(self.preview.name)

        # remove inline images
        for image in self.get_image_urls():
            image = os.path.basename(image)
            image = os.path.join(paths.MEDIA_IMAGE_DIR, image)
            lib.delete_file(image)

        super(Thought, self).delete(*args, **kwargs)

    def __str__(self):
        return self.__unicode__()

    def __unicode__(self):

blog/templates/blog/about.html
{% extends 'blog/templates/template_default.html' %}
{% load staticfiles %}

{% block content %}
<h2><a name="about-slacker-paradise">About Slacker Paradise…</a></h2>
<p>A slacker paradise is exactly what it sounds like. A slacker paradise is that place in your head where you think about awesome shit when you are supposed to be sitting in your cubicle doing something really boring. Why would you wanna make TPS reports for some butt-fuck when you could be here?</p>
<h3><a name="the-art-of-slack">The Art of Slack</a></h3>
<p>Being a slacker, also known as “slacking”, is a way of life. Being a slacker is actually really hard. This is not a joke.</p>
<blockquote class="pull-quote">
    <p>Being a slacker means not doing anything that anyone tells you to, and especially not doing the thing you are supposed to be doing at this very minute.</p>
</blockquote>
<p>Being a slacker means not doing anything that anyone tells you to, and especially not doing the thing you are supposed to be doing at this very minute. A slacker doesn't even do the thing he/she decided to do in the first place. The only reason for a slacker to do anything at all is because it's fucking awesome. Things will work themselves out. A slacker follows the art of <em>Slacker Zen</em>.</p>
<h3><a name="slacker-zen">Slacker Zen? What the hell?</a></h3>
<blockquote>
    <p>Scott Pilgrim is a 23-year-old jobless type of kid living in Toronto. He has a few jerky friends and they're in a band together... Scott has hit this point in his life where he's in a sort of slacker Zen state. Nothing really bothers him and he's always pretty cheery, in a laid-back, kind of slightly disturbing way… Scott is less complex than most people, and that suits him fine. He plays video games, cooks dinner for his friends and roommates, watches television, refrains from smoking or drinking or having sex with his desperately horny 17-year old girlfriend, and has a great old time of it all.</p>
    <cite>Bryan Lee O'Malley</cite>
</blockquote>
<p>Scott Pilgrim is the freaking shit. He experiences a prolonged state of Slacker Zen before he ascends to a higher plane of existence and accepts his responsibilities as a rad dude.</p>
<h3><a name="slacker-manifesto">Slacker Manifesto</a></h3>
<p>This dude's <a href="http://brodzinski.com/slacker-manifesto-html" target="_blank">website</a> has a page on it that's called "Slacker Manifesto". What the fuck is this shit. This page comes from a software project management blog. People like this make slackers look bad. This isn't slacking, this is hip corporate-speak bullshit. Just because you're doing nothing at a given moment doesn't mean you are a slacker, it means you're human. It takes dedication to do nothing <em>all the time</em>. Get outta here with this casual bullshit. This is a REAL slacker manifesto:</p>
<blockquote>
    <p>We will forsake our jobs.</p>
    <p>We will leave them behind us and become one with this earth. We have no nation, no philosophy, no ideology. We go where we're needed, slacking, not for government, but for ourselves.</p>
    <p>We need no reason to slack.<br>We slack because we can.</p>
    <p>We will be the deterrent for those with no other recourse. We are slackers without borders, our purpose defined by the era we live in.</p>
    <p>We will sometimes have to sell ourselves and services. If the times demand it, we'll be stoners, deadbeats, and gypsies.</p>
    <p>And yes, we may all be headed straight to hell. But what better place for us than this?</p>
    <p>It's our only home.<br>Our heaven and our hell.<br>This is Slacker Paradise.</p>
    <cite>Slack Boss</cite>
</blockquote>
<p>And don't be fooled by what people say. A slacker is not a loser, nor is slacking a bad thing. That's just propaganda spouted by people who have already been brainwashed into thinking they should waste their lives away working for the man because they think they need to be "productive". There are have been many famous and influential people who are slackers. For example, Mark Zuckerberg, Steve Jobs, and Bill Gates are among the ranks of high level slackers. They dropped out of college halfway through and accidentally made huge companies. Amazing what kinds of things you can do by accident?</p>
<p>Anyway, not all slackers are huge computer nerds. Gandhi was another famous slacker who was able to bring about widespread social change over his refusal to do anything at all. It was quite amazing, watching him sit there doing nothing, being so in tune with his Slacker Zen that he couldn't even muster the will to eat food until he almost died.</p>
<p>Similarly, Rosa Parks, did the same almost fifty years later in the middle of a fit of slacking so hard that she was unable to get up from her seat on the bus. And most of all, don’t forget me, Cory Parsnipson. I'm a bad dude. Nuff said.</p>

<hr>

<h2><a name="technology-stack">Technology Stack</a></h2>
<p>Slacker Paradise was made with:</p>
<ul>
    <li><a href="https://www.djangoproject.com/" target="_blank">Django 1.7.1</a></li>
    <li><a href="https://github.com/matthewwithanm/django-imagekit" target="_blank">Django ImageKit</a></li>
    <li><a href="https://pillow.readthedocs.org/" target="_blank">Python Pillow</a></li>
    <li><a href="https://boto.readthedocs.org/en/latest/" target="_blank">Boto</a> with <a href="https://django-storages.readthedocs.org/en/latest/" target="_blank">Django Storages</a></li>
    <li><a href="http://initd.org/psycopg/" target="_blank">psycopg2</a> optimized with <a href="https://pypi.python.org/pypi/django-postgrespool" target="_blank">Django Postgrespool</a> and <a href="https://pypi.python.org/pypi/dj-database-url" target="_blank">Dj Database URL</a></li>
    <li><a href="https://github.com/Pylons/waitress" target="_blank">waitress</a></li>
    <li><a href="http://www.celeryproject.org/" target="_blank">celery</a></li>
    <li><a href="https://redis.io/" target="_blank">redis</a></li>
    <li><a href="http://www.crummy.com/software/BeautifulSoup/" target="_blank">BeautifulSoup</a></li>
    <li><a href="http://foundation.zurb.com/" target="_blank">Foundation 5</a></li>
    <li><a href="http://jquery.com/" target="_blank">jQuery</a></li>
    <li><a href="http://www.tinymce.com/" target="_blank">TinyMCE</a></li>
    <li><a href="http://www.seleniumhq.org/" target="_blank">Selenium</a></li>
    <li><a href="http://docs.python-guide.org/en/latest/dev/virtualenvs/" target="_blank">VirtualEnv</a></li>
    <li><a href="http://en.wikipedia.org/wiki/Beer" target="_blank">Beer</a></li>
    <li>Probably more stuff that I can't remember</li>
</ul>

<p>Slacker Paradise is hosted on <a href="http://www.heroku.com" target="_blank">Heroku</a> with static file hosting on <a href="http://aws.amazon.com/s3/" target="_blank">Amazon S3</a> and domain registration by <a href="http://www.namecheap.com" target="_blank">NameCheap</a>. The text is laid out in <a href="http://www.google.com/fonts/specimen/Roboto" target="_blank">Roboto</a> and <span class="eurostile-black big"><a href="https://www.myfonts.com/fonts/urw/eurostile/" target="_blank">Eurostile Black</a></span>.</p>
{% endblock %}

{% block side %}
<div id="author-block" class="group">
    <h2><a name="cory-parsnipson">About Cory Parsnipson</a></h2>
    <img class="left" src="{% static 'images/cparsnipson.png' %}">
    <p>Cory Parsnipson is a slacker. He graduated with absolutely no honors from <a href="https://www.facebook.com/CaldwellU" target="_blank"> Caldwell University</a>, class of '12. He is a super smart person and handsome. He is popular + has many friends.</p>

    <p>Send Cory Parsnipson <a href="#">hate mail</a>.</p>
    <p>Friend Cory Parsnipson on <a href="https://www.facebook.com/cory.parsnipson" target="_blank">facebook</a>. (Tell him he sucks)</p>
    <hr>

    <h2>Contents</h2>
    <a class="reverse-color sidebar" href="#about-slacker-paradise">About Slacker Paradise...</a>
    <a class="reverse-color sidebar" href="#the-art-of-slack">The Art of Slack</a>
    <a class="reverse-color sidebar" href="#slacker-zen">Slacker Zen? What the hell?</a>
    <a class="reverse-color sidebar" href="#slacker-manifesto">Slacker Manifesto</a>
    <a class="reverse-color sidebar" href="#technology-stack">Technology Stack</a>
</div>
{% endblock %}

blog/templates/blog/books.html
{% extends 'blog/templates/template_default.html' %}
{% load staticfiles %}

{% block content %}
<h2>
    Cory's Reading List
    {% if request.user.is_authenticated and request.user.is_superuser %}
    <a class="edit" href="{% url 'dashboard-books' %}">edit</a>
    {% endif %}
</h2>
<hr class="header">

<h3>Currently Reading/Wish List</h3>
<div class="book-list">
    {% for book in wish_list %}
    <div class="book-book-result book-book-result-hover group">
        <img src="{{ book.cover }}" class="left">
        <p class="title">
            {{ book.title }}
            {% if request.user.is_authenticated and request.user.is_superuser %}
            <a class="edit" href="{% url 'dashboard-books' %}?b={{ book.id }}">edit</a>
            {% endif %}
        </p>
        <p class="author">{{ book.author }}</p>
        {% if book.favorite %}<span class="favorite" title="Cory's Favorites">&#x2605;</span>{% endif %}
        <a class="overlay" href="{{ book.link }}" target="_blank"></a>
    </div>
    {% empty %}
    <p class="empty">There are no books in the list.</p>
    {% endfor %}
</div>

<h3>Recently Read</h3>
<div class="book-list">
    {% for book in read_list %}
    <div class="book-book-result book-book-result-hover group">
        <img src="{{ book.cover }}" class="left">
        <p class="title">
            {{ book.title }}
            {% if request.user.is_authenticated and request.user.is_superuser %}
            <a class="edit" href="{% url 'dashboard-books' %}?b={{ book.id }}">edit</a>
            {% endif %}
        </p>
        <p class="author">{{ book.author }}</p>
        <p class="description">{{ book.description }}</p>
        <p class="date">Added on {{ book.date_published|date:"F j, Y g:i A" }}</p>
        {% if book.favorite %}<span class="favorite" title="Cory's Favorites">&#x2605;</span>{% endif %}
        <a class="overlay" href="{{ book.link }}" target="_blank"></a>
    </div>
    {% empty %}
    <p class="empty">There are no books in the list.</p>
    {% endfor %}
</div>

{% include "blog/templates/template_pagination.html" with paginator=paginator pages=pagination %}
{% endblock %}

{% block side %}
<h2>Cory's favorite types of books...</h2>
<p>...are old science fiction, and really convoluted comedy books (fictional or otherwise). In particular, he enjoys <a href="http://johndiesattheend.com/" target="_blank">John Dies at the End</a> by <a href="http://johndiesattheend.com/about.php" target="_blank">David Wong</a>.</p>


<h2>Books are awesome</h2>
<p>Slackers should totally read a lot of books. It sounds kind of counterintuitive, but actually it's quite useful. For instance, you can pretend to read a book on the beach and then accidentally on purpose fall asleep on the beach. A book can also be used to avoid talking to someone who would take a lot of effort to talk to. This is because the fact that you have a book open and grimacing at it makes it seem like you are working hard when in reality, you are thinking about ice cream. Sometimes if you are sitting in the right place, people will take a picture of you doing this, thinking you are famous and super smart.</p>
{% endblock %}

blog/templates/blog/default_page.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>SP :: {{ page_title }}</title>

    <!-- css includes -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">

    <!-- script includes -->
    <script type="text/javascript" src="{% static 'script/framework.js' %}"></script>
    <script type="text/javascript" src="{% static 'script/blog.js' %}"></script>

    {% block http_headers %}
    <!-- template specific head tags should be added here -->
    {% endblock %}
</head>
<body>

<div id="c-header">
    <h1><a href="{% url 'index' %}">Slacker Paradise</a></h1>
</div>

<div id="c-body" class="group">
    <div id="c-content">
        <!-- navigation structure -->
        <div id="c-nav">
            <ul class="nav">
                <li><a href="{% url 'index' %}">Home</a></li>
                <li><a href="{% url 'about' %}">About</a></li>
                <li><a href="{% url 'idea_list' %}">Ideas</a></li>
                <li class="right_justified">
                    {% if user.is_authenticated %}
                    <a href="{% url 'dashboard' %}">Dashboard</a>
                    {% else %}
                    <a href="{% url 'login_page' %}">Login</a>
                    {% endif %}
                </li>
            </ul>
        </div>

        <div id="c-content-inner">
            {% if messages %}
            <!-- flash message area -->
            <ul class="messages" style="list-style-type: none; color: red; font-weight: bold">
                {% for message in messages %}
                <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}

            <!-- main content -->
            {% block content %}
            There is no content on this page.
            {% endblock %}
        </div>

        <!-- footer -->
        <div id="c-footer">
            {% block footer %}
            {% endblock %}
        </div>
    </div>

    <!-- side content -->
    <div id="c-side">
        <div id="c-side-inner">
            {% block side %}
            <p>Sidebar content.</p>
            {% endblock %}
        </div>
    </div>
</div>

</body>
</html>

blog/templates/blog/login.html
{% extends "blog/templates/template_default.html" %}

{% block content %}
{% if not user.is_authenticated %}
<p>Please enter in your credentials:</p>

<form class="login-form" action="{% url 'login' %}" method="post">
    {% csrf_token %}
    <table>
        <tbody>
        <tr>
            <td class="shrink">{{ login_form.username.label_tag }}</td>
            <td>{{ login_form.username }}</td>
        </tr>
        <tr>
            <td class="shrink">{{ login_form.password.label_tag }}</td>
            <td>{{ login_form.password }}</td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Login"></td>
        </tr>
        </tbody>
    </table>
</form>
{% endif %}
{% endblock %}

blog/templates/blog/logout.html
{% extends "blog/templates/template_default.html" %}

{% block http_headers %}
<meta http-equiv="refresh" content="5;url={% url 'index' %}">
{% endblock %}

{% block content %}
<p>You will be redirected shortly. If you do not wish to wait, please click <a href="{% url 'index' %}">here.</a></p>
{% endblock %}